### PR TITLE
Bugfix for iOS missing params in deeplinks and Android applinks 

### PR DESCRIPTION
**Pull request by harshabonthu**
Current Implementation of plugin uses Cordova-Universal-links-plugin to depend on App associates file generation, but that conflicts with Intent filters injecting code and also conflicts in override of application:continueUserActivity:restorationHandler: method to capture params when app resumes with a deeplink click.

As a result of these conflicts, Branch plugin cant capture the params from deep links and intents filters needed to support deeplinks are not being added properly to Android Manifest file.

### CODE REVIEW

**Comment by aaustin** [comment]
Um. Amazing! Can we send you a hoodie? https://branch.io/branch-referral-program-claim-reward/

**Comment by harshabonthu** [comment]
sure ;)

**Comment by jestoniyap** [comment]
@harshabonthu seems like this is using the branch framework but we are using the actual source files on master. Were you using an older codebase?

**Comment by aaustin** [comment]
We're going to merge this in, and then @jestoniyap is going to replace the framework with the raw source so that the NPM won't barf.

**Pull request merged**
