### PR TITLE
Support for legacy share sheets

### PR DESCRIPTION
**Pull request by aaustin**
@renesansz This will take care of the issue reported in
https://github.com/BranchMetrics/Cordova-Ionic-PhoneGap-Deferred-Deep-Linking-SDK/issues/112

### CODE REVIEW

**Comment by renesansz** [comment]
Hmm...weird, from my point of view, I thought that the only problem was npm wasn't able to fetch the latest update from the repo.

Based on this error:
```
showShareSheet(this.args.getInt(0), this.args.getJSONObject(1), this.args.getJSONObject(2));
^
required: int,JSONObject,JSONObject,String
found: int,JSONObject,JSONObject
```
It points out to the old implementation of the method wherein it does not take `String` parameter for the custom share message text.

**Comment by aaustin** [comment]
Hmm - not sure how that would happen on upgrading.

**Comment by renesansz** [comment]
I'll try the change first, currently my implementation works well.
Not sure if this is the cause of the error.

**Comment by renesansz** [comment]
@aaustin , Just have checked the PR, it seems it works well. 👍

**Pull request merged**
