### PR TITLE
Implement iOS9 Universal Links

### PR DESCRIPTION
**Pull request by jsaleigh**

### CODE REVIEW

**Comment by jsaleigh** [comment]
@dmitrig01 @chanian would either of you be able to have a look at this PR by chance?

**Comment by dmitrig01** [comment]
perhaps @derrickstaten can help

**Comment by dmitrig01** [comment]
or @danwalkowski

**Comment by derrickstaten** [comment]
@jsaleigh I have never run the testbed app, but if you run it, I can help you test Universal Links

**Comment by heks** [comment]
Is there anything we need to do to integrate this (like with the javascript)?

**Comment by jsaleigh** [comment]
Hi @heks! No, you shouldn't need anything else to use this (other than the usual Universal Links setup with a apple-app-site-association file, entitlements, etc.)

**Comment by jsaleigh** [comment]
@danwalkowski @derrickstaten PTAL when you can so we can make this real :)

**Comment by chanian** [comment]
:+1:

**Comment by danwalkowski** [comment]
@jsaleigh I'm looking through it now.  Sorry for the delay.

**Comment by danwalkowski** [comment]
:+1:  This looks reasonable to me.  I can't prove it's correct without lots of effort, which I'm going to assume that you, John, have put in, as the interested party. :)

**Pull request merged**
